name: Download GitHub Release Assets

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  download-assets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download release assets
      uses: houqp/download-release-assets@v1
      with:
        release: 16.09.2024
        repo: crisarbebvc/vericlear
        match: ".jar"